apiVersion: v1
kind: Service
metadata:
  name: mandarincantonese-api-service-qa
  labels:
    app: mandarincantonese-api
    type: mandarincantonese-api-service
    environment: qa
spec:
  ports:
  - port: 80
    targetPort: 8042
  selector:
    app: mandarincantonese-api
    environment: qa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandarincantonese-api-deployment-qa
  labels:
    app: mandarincantonese-api
    type: mandarincantonese-api-server
    environment: qa
spec:
  selector:
    matchLabels:
      app: mandarincantonese-api
      type: mandarincantonese-api-server
      environment: qa
  replicas: 1
  template:
    metadata:
      labels:
        app: mandarincantonese-api
        type: mandarincantonese-api-server
        environment: qa
    spec:
      containers:
      - name: mandarincantonese-api-qa
        image: lucwastiaux/mandarin-cantonese-api:v0.2
        ports:
        - containerPort: 8042